version: "3.8"

services:
  backend:
    build:
      dockerfile: ./backend/Dockerfile
    container_name: backend
    volumes:
      - ./backend:/opt/app/api
    ports:
    - 8080:8080
  frontend:
    container_name: frontend
    build: ./app
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
  # app:
  #   build:
  #     dockerfile: ./app/Dockerfile
  #   # container_name: front
  #   volumes:
  #     - ./app:/app
  #   ports:
  #     - 3000:3000